replicaCount: 1
HistoryLimit: 3
image:
  repository: mrvgavrilyuk/nginx-stats
  tag: latest
  pullPolicy: Always
service:
  type: ClusterIP
  port: 80
  metrics: 9113
ingress:
  enabled: true
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi
