apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: Prometheus
  name: pods-watch-list-get
rules:
  - verbs:
      - watch
      - list
      - get
    resources: ["pods"]
    apiGroups: [""]