apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentservice
  labels:
    app: paymentservice
spec:
  selector:
    matchLabels:
      app: paymentservice
  replicas: 3
  template:
    metadata:
      labels:
        app: paymentservice
    spec:
      containers:
      - name: server
        image: mrvgavrilyuk/hipster-payment:v0.0.1
        ports:
          - containerPort: 50051
        env:
        - name: PORT
          value: "50051"
        - name: COLLECTOR_SERVICE_ADDR
          value: "opentelemetrycollector:4317"
        - name: DISABLE_PROFILER
          value: "1"
