apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-service
  labels:
    app: {{ .Chart.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
      name: http
    - port: {{ .Values.service.metrics }}
      targetPort: {{ .Values.service.metrics }}
      protocol: TCP
      name: metrics
  selector:
    app: {{ .Chart.Name }}
