apiVersion: v1
kind: Pod
metadata:
  name: mypod
  labels:
    app: mypod
spec:
  initContainers:
    - name: init
      image: busybox:1.31.0
      command: ['sh', '-c', 'wget -O- https://tinyurl.com/otus-k8s-intro | sh']
      volumeMounts:
        - name: app
          mountPath: /app
  containers:
    - name: mypod-ct
      image: mrvgavrilyuk/homework:test
      volumeMounts:
        - name: app
          mountPath: /app
  volumes:
  - name: app
    emptyDir:
      sizeLimit: 500Mi